# Site settings
title: MSML 2027
description: 6th MSML International Conference - Mathematical theory and algorithms of machine learning
url: "https://msml2027.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - DEPLOY.md

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
